G001:
  - kennwort
G002:
  - anmeldedaten
G003:
  - dls
G004:
  - taskleiste
G005:
  - fusion
G006:
  - endgeraet
G007:
  - one number
G008:
  - clir
G009:
  - deaktivieren
G010:
  - kontakte
G011:
  - konferenz
G012:
  - papierstau
G013:
  - duplex
G014:
  - patrone
G015:
  - abwesenheitsagent
G016:
  - stellvertreter
G017:
  - raum
G018:
  - proxy
G019:
  - webgateway
G020:
  - starttls
G021:
  - forms
G022:
  - postfach
G023:
  - senden von
G024:
  - zugriff
G025:
  - greenshot
G026:
  - abwesenheit
G027:
  - halbtagig
G028:
  - ordnerberechtigungen
G029:
  - passwortmanager
G030:
  - serverseitig
G031:
  - kalendergruppe
G032:
  - warnungen
G033:
  - ssl-analyse
G034:
  - vertrauensstellung
G035:
  - sonderzeichen
G036:
  - prasenzstatus
G037:
  - anrufumleitung
G038:
  - internetprofile
G039:
  - zwischenablage
G040:
  - test
G041:
  - druckqualitat
